Backup sidecar for postgres and mariadb
sapcc/openstack-helm pull request #21
Opened 2016-12-19 15:46 UTC by Dexus

creates a backup sidecar for postgres and mariadb.

ATTENTION: The values of postgres/mariadb needs a update to the last backup.image version - but we have current problems to upload it.

2016-12-19 16:27 UTC, fwiesel commented
Can I convince you to use the hook `/docker-entrypoint-maintaindb.d/` for creating/maintaining the required users instead of having an own special script?

Any script (or sql file) in the  configmaps `db-maintain-<name>` will be executed on startup of the respective database.

2016-12-20 07:33 UTC, fwiesel commented
Hi,

also it should not be located under `bin/`, but directly in that configmap, and end on `.sh`.
See here, how it will be [invoked](https://github.wdf.sap.corp/monsoon-docker/monsoon-postgres/blob/dba7c12f3ddab8e152f1fa7b475afaf63f89f45c/docker-entrypoint.sh#L103-L111).

2016-12-20 09:26 UTC, BugRoger commented on postgres/values.yaml
> +  image: hub.global.cloud.sap/c5211168/monsoon3-backup:0.1.2
This needs to be configurable with a value. The default should be a public image `sapcc/backup-tools:v0.1.2`. Internally we overwrite this with out image from hub.global.cloud.sap.

2016-12-20 09:27 UTC, BugRoger commented on mariadb/values.yaml
> +  image: hub.global.cloud.sap/c5211168/monsoon3-backup:0.1.2
This needs to be configurable with a value. The default should be a public image sapcc/backup-tools:v0.1.2. Internally we overwrite this with out image from hub.global.cloud.sap.

2016-12-20 09:28 UTC, BugRoger commented on mariadb/templates/backup-configmap.yaml
> +  mysql.backup.incr: 3 hours
Can we make this configurable via Helm values? And defaults in the chart.

2016-12-20 09:29 UTC, BugRoger commented on mariadb/values.yaml
>  image: mariadb:10.1
make configurable

2016-12-20 09:29 UTC, BugRoger commented on postgres/templates/backup-configmap.yaml
> +  postgres.backup.full: 3 days
make configurable

2016-12-20 09:48 UTC, BugRoger requested changes
make stuff more configurable

2016-12-20 10:17 UTC, Dexus commented
Can you explain what is still needed to make the stuff more configurable? What am I currently missing?

2016-12-20 10:27 UTC, urfuwo commented
@Dexus see the review above. 
* location and name of image need to be value. 
* backup scheduling behaviour need to be values.
* image need to be on sapcc with requested name
* image need to be published on hub.global interneally with same name
* build make file and docker container need to be published on sapcc/containers -> speak to Michael for setup.
* after merge: next concourse build for container with publishing to hub.docker and hub.global internally.

2016-12-20 15:56 UTC, BugRoger approved these changes

2016-12-20 16:04 UTC, fwiesel commented
I see another problem with `postgres/templates/maintain-configmap.yaml`, it now conflicts with the individual maintain configmaps (Here an [example](https://github.com/sapcc/openstack-helm/blob/master/neutron/templates/db-maintain-configmap.yaml)).

In case of neutron (as the example given), you create now two `db-maintain-neutron` configmaps,
which in the best case will fail, or maybe simply end up applied in a semi-random order.

2016-12-22 14:59 UTC, closed without merging