Adding vspc deployment file
sapcc/openstack-helm pull request #47
Opened 2017-03-16 16:02 UTC by rajivmucheli

we created vmware-vspc-deployment.yaml, as there was a change in plan and opted for only 1 file. vmware-vspc-service.yaml has to be created.

2017-03-16 16:07 UTC, fwiesel commented on nova/templates/vmware-vspc-deployment.yaml
> +spec:
Hi,

the spec following the is a service definition.
Can you please move it to a separate file, and set the correct `kind`, `apiVersion` and `metadata` for it.

2017-03-17 04:35 UTC, rajivmucheli commented
Updated the comments and created vmware-vspc-service.yaml

2017-03-17 08:58 UTC, fwiesel commented on nova/templates/vmware-vspc-service.yaml
> +   name: nova-vmware-vspc
This has to be intended by one. It is an attribute of the selector.
The selector of the nodeport should choose all pods with the name `nova-vmware-vspc`

2017-03-17 09:01 UTC, fwiesel commented on nova/templates/vmware-vspc-deployment.yaml
> +          imagePullPolicy: IfNotPresent
The container is missing a specification of the ports it is exposing.
Check here for how it works: https://kubernetes.io/docs/tutorials/connecting-apps/connecting-frontend-backend/

2017-03-20 08:09 UTC, fwiesel commented on nova/templates/vmware-vspc-service.yaml
> +       targetPort: admin
Here the indentation is too deep.

2017-03-20 08:22 UTC, fwiesel commented on nova/templates/vmware-vspc-service.yaml
> +  externalIPs: ["10.44.11.151"]
This should be a variable, which we will define in the regional setup

2017-04-06 12:38 UTC, fwiesel requested changes

2017-04-06 12:38 UTC, fwiesel commented on vmware-vspc-deployment.yaml
> +spec:
The spec for the node-port has to be removed from this file

2017-04-06 12:38 UTC, fwiesel commented on nova/templates/vspc-configmap.yaml
> +{{ tuple "etc/_ config.json.tpl.tpl" . | include "template" | indent 4 }}
Could you move the config.json and the vspc.conf  into this file?

2017-04-07 06:09 UTC, fwiesel commented on nova/templates/vspc-configmap.yaml
> +   command : "vmware-vspc --config-file vspc.conf"
Hi, now the config.json will only contain
`command : "vmware-vspc --config-file vspc.conf"`, which is not a proper json format.

2018-12-10 09:14 UTC, fwiesel commented
Closing as the project is deprecated in favour of sapcc/helm-charts

2018-12-10 09:14 UTC, closed without merging